name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports/tests/
      if: always()
      
    - name: Send email on success
      uses: dawidd6/action-send-mail@v3
      if: success()
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: $prit-Savani
        password: $PritSAVANI06@#
        subject: Build Successful - OnTrackTDD
        body: Your build for OnTrackTDD completed successfully! All tests have passed.
        to: pritsavani06@gmail.com
        from: GitHub Actions
        
    - name: Send email on failure
      uses: dawidd6/action-send-mail@v3
      if: failure()
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: $prit-Savani
        password: $PritSAVANI06@#
        subject: Build Failed - OnTrackTDD
        body: Your build for OnTrackTDD failed! Please check the test results and fix the issues.
        to: pritsavani06@gmail.com
        from: GitHub Actions 